/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.inatel.projetopetshop.view;

import br.inatel.projetopetshop.DAO.DonoAnimalDAO;
import br.inatel.projetopetshop.model.Animal;
import br.inatel.projetopetshop.model.Banho;
import br.inatel.projetopetshop.model.Consulta;
import br.inatel.projetopetshop.model.DonoAnimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juninho
 */
public class TelaInfoCliente extends javax.swing.JFrame {
    
    DonoAnimalDAO aDao = new DonoAnimalDAO();
    private ArrayList<Animal> animaisP = new ArrayList<>();
    private ArrayList<Banho> banhosP = new ArrayList<>();
    private ArrayList<Consulta> consultasP = new ArrayList<>();
    
    private static String senha;
    private static String cpfCl;

    /** Creates new form TelaInfoCliente */
    public TelaInfoCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tbAnimal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labNomeC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labCpfC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labIdadeC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labEmailC = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labEnderecoC = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labTelefoneC = new javax.swing.JLabel();
        btnSairCliente = new javax.swing.JButton();
        btnCadastrarAnimal = new javax.swing.JButton();
        btnEcxcluirAnimal = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labSenha = new javax.swing.JLabel();
        mostrarSenha = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnSairAnimal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNome = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEspecie = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listIdade = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPeso = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listVacinado = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        listID = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listCpfAux = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        listDataBanho = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        listIdAnimalBanho = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        listHorarioBanho = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        listValorBanho = new javax.swing.JList<>();
        btnSairBanho = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        listNumCons = new javax.swing.JList<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        listCrmvCons = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        listIdAnimalCons = new javax.swing.JList<>();
        jScrollPane15 = new javax.swing.JScrollPane();
        listDataCons = new javax.swing.JList<>();
        jScrollPane16 = new javax.swing.JScrollPane();
        listHorarioCons = new javax.swing.JList<>();
        jScrollPane17 = new javax.swing.JScrollPane();
        listValorCons = new javax.swing.JList<>();
        btnSairCons = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfAttIdade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfAttEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfSenhaAtual = new javax.swing.JPasswordField();
        btnAtualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfAttTelefone = new javax.swing.JFormattedTextField();
        tfAttSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbAnimal.setBackground(new java.awt.Color(0, 153, 153));
        tbAnimal.setForeground(new java.awt.Color(0, 0, 0));
        tbAnimal.setToolTipText("");
        tbAnimal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbAnimalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nome:");

        labNomeC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labNomeC.setForeground(new java.awt.Color(0, 0, 0));
        labNomeC.setText("?");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("CPF:");

        labCpfC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labCpfC.setForeground(new java.awt.Color(0, 0, 0));
        labCpfC.setText("?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Idade:");

        labIdadeC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labIdadeC.setForeground(new java.awt.Color(0, 0, 0));
        labIdadeC.setText("?");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("E-mail:");

        labEmailC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labEmailC.setForeground(new java.awt.Color(0, 0, 0));
        labEmailC.setText("?");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Endereço:");

        labEnderecoC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labEnderecoC.setForeground(new java.awt.Color(0, 0, 0));
        labEnderecoC.setText("?");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Telefone:");

        labTelefoneC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labTelefoneC.setForeground(new java.awt.Color(0, 0, 0));
        labTelefoneC.setText("?");

        btnSairCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSairCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnSairCliente.setText("Sair");
        btnSairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairClienteActionPerformed(evt);
            }
        });

        btnCadastrarAnimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarAnimal.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrarAnimal.setText("Cadastrar Animal");
        btnCadastrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAnimalActionPerformed(evt);
            }
        });

        btnEcxcluirAnimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEcxcluirAnimal.setForeground(new java.awt.Color(0, 0, 0));
        btnEcxcluirAnimal.setText("Excluir Animal");
        btnEcxcluirAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcxcluirAnimalActionPerformed(evt);
            }
        });

        btnExcluirConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirConta.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirConta.setText("Excluir Minha Conta");
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Senha:");

        labSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labSenha.setForeground(new java.awt.Color(0, 0, 0));
        labSenha.setText("?");

        mostrarSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mostrarSenha.setForeground(new java.awt.Color(0, 0, 0));
        mostrarSenha.setText("Mostrar");
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labNomeC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labCpfC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labIdadeC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labEmailC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labEnderecoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labTelefoneC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarSenha)))
                        .addGap(0, 308, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCadastrarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEcxcluirAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluirConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labNomeC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labCpfC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labIdadeC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labEmailC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labEnderecoC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labTelefoneC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labSenha)
                    .addComponent(mostrarSenha))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEcxcluirAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairCliente)
                    .addComponent(btnExcluirConta))
                .addContainerGap())
        );

        tbAnimal.addTab("Cliente", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnSairAnimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSairAnimal.setForeground(new java.awt.Color(0, 0, 0));
        btnSairAnimal.setText("Sair");
        btnSairAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairAnimalActionPerformed(evt);
            }
        });

        listNome.setBackground(new java.awt.Color(255, 255, 255));
        listNome.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jScrollPane1.setViewportView(listNome);

        listEspecie.setBackground(new java.awt.Color(255, 255, 255));
        listEspecie.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Espécie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jScrollPane2.setViewportView(listEspecie);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        listIdade.setBackground(new java.awt.Color(255, 255, 255));
        listIdade.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Idade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jScrollPane3.setViewportView(listIdade);

        listPeso.setBackground(new java.awt.Color(255, 255, 255));
        listPeso.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Peso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jScrollPane4.setViewportView(listPeso);

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        listVacinado.setBackground(new java.awt.Color(255, 255, 255));
        listVacinado.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Vacinado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jScrollPane5.setViewportView(listVacinado);

        listID.setBackground(new java.awt.Color(255, 255, 255));
        listID.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Nº Cartão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jScrollPane6.setViewportView(listID);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSairAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairAnimal)
                .addContainerGap())
        );

        tbAnimal.addTab("Animal", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        listCpfAux.setBackground(new java.awt.Color(255, 255, 255));
        listCpfAux.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "CPF Aux", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listCpfAux.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listCpfAux.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane7.setViewportView(listCpfAux);

        listDataBanho.setBackground(new java.awt.Color(255, 255, 255));
        listDataBanho.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listDataBanho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listDataBanho.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane9.setViewportView(listDataBanho);

        listIdAnimalBanho.setBackground(new java.awt.Color(255, 255, 255));
        listIdAnimalBanho.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Nº Cartão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listIdAnimalBanho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listIdAnimalBanho.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane10.setViewportView(listIdAnimalBanho);

        listHorarioBanho.setBackground(new java.awt.Color(255, 255, 255));
        listHorarioBanho.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Horário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listHorarioBanho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listHorarioBanho.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane8.setViewportView(listHorarioBanho);

        listValorBanho.setBackground(new java.awt.Color(255, 255, 255));
        listValorBanho.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listValorBanho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listValorBanho.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane11.setViewportView(listValorBanho);

        btnSairBanho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSairBanho.setForeground(new java.awt.Color(0, 0, 0));
        btnSairBanho.setText("Sair");
        btnSairBanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairBanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairBanho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(btnSairBanho)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbAnimal.addTab("Banhos", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        listNumCons.setBackground(new java.awt.Color(255, 255, 255));
        listNumCons.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Nº Cons.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listNumCons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listNumCons.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane12.setViewportView(listNumCons);

        listCrmvCons.setBackground(new java.awt.Color(255, 255, 255));
        listCrmvCons.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "CRMV Vet.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listCrmvCons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listCrmvCons.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane13.setViewportView(listCrmvCons);

        listIdAnimalCons.setBackground(new java.awt.Color(255, 255, 255));
        listIdAnimalCons.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Nº Cartão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listIdAnimalCons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listIdAnimalCons.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane14.setViewportView(listIdAnimalCons);

        listDataCons.setBackground(new java.awt.Color(255, 255, 255));
        listDataCons.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listDataCons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listDataCons.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane15.setViewportView(listDataCons);

        listHorarioCons.setBackground(new java.awt.Color(255, 255, 255));
        listHorarioCons.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Horário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listHorarioCons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listHorarioCons.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane16.setViewportView(listHorarioCons);

        listValorCons.setBackground(new java.awt.Color(255, 255, 255));
        listValorCons.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        listValorCons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listValorCons.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane17.setViewportView(listValorCons);

        btnSairCons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSairCons.setForeground(new java.awt.Color(0, 0, 0));
        btnSairCons.setText("Sair");
        btnSairCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairConsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSairCons, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jScrollPane15)
                    .addComponent(jScrollPane14)
                    .addComponent(jScrollPane13)
                    .addComponent(jScrollPane12)
                    .addComponent(jScrollPane17))
                .addGap(18, 18, 18)
                .addComponent(btnSairCons)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbAnimal.addTab("Consultas", jPanel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Atualizar Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Atualizar Idade:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Atualizar Senha:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Atualizar Endereço:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Senha Atual:");

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Limpar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Atualizar Telefone:");

        try {
            tfAttTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfAttIdade)
                    .addComponent(tfAttEndereco)
                    .addComponent(tfSenhaAtual)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(tfAttTelefone)
                    .addComponent(tfAttSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(tfAttEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfAttTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAttIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAttSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnCancelar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        tbAnimal.addTab("Atualizações", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbAnimal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbAnimal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairClienteActionPerformed
        sair();
    }//GEN-LAST:event_btnSairClienteActionPerformed

    private void btnCadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAnimalActionPerformed
        cadastrarAnimal();
    }//GEN-LAST:event_btnCadastrarAnimalActionPerformed

    private void btnEcxcluirAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcxcluirAnimalActionPerformed
       excluirAnimal();
    }//GEN-LAST:event_btnEcxcluirAnimalActionPerformed

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        excluirConta();
    }//GEN-LAST:event_btnExcluirContaActionPerformed

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        if(mostrarSenha.isSelected()){
            mostrarSenha.setText("Esconder");
            labSenha.setText(senha);
        }else{
            mostrarSenha.setText("Mostrar");
            labSenha.setText("********");
        }
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void tbAnimalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbAnimalAncestorAdded
        
    }//GEN-LAST:event_tbAnimalAncestorAdded

    private void btnSairConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairConsActionPerformed
        sair();
    }//GEN-LAST:event_btnSairConsActionPerformed

    private void btnSairBanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairBanhoActionPerformed
        sair();
    }//GEN-LAST:event_btnSairBanhoActionPerformed

    private void btnSairAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairAnimalActionPerformed
        sair();
    }//GEN-LAST:event_btnSairAnimalActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        atualizar();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInfoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrarAnimal;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEcxcluirAnimal;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnSairAnimal;
    private javax.swing.JButton btnSairBanho;
    private javax.swing.JButton btnSairCliente;
    private javax.swing.JButton btnSairCons;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labCpfC;
    private javax.swing.JLabel labEmailC;
    private javax.swing.JLabel labEnderecoC;
    private javax.swing.JLabel labIdadeC;
    private javax.swing.JLabel labNomeC;
    private javax.swing.JLabel labSenha;
    private javax.swing.JLabel labTelefoneC;
    private javax.swing.JList<String> listCpfAux;
    private javax.swing.JList<String> listCrmvCons;
    private javax.swing.JList<String> listDataBanho;
    private javax.swing.JList<String> listDataCons;
    private javax.swing.JList<String> listEspecie;
    private javax.swing.JList<String> listHorarioBanho;
    private javax.swing.JList<String> listHorarioCons;
    private javax.swing.JList<String> listID;
    private javax.swing.JList<String> listIdAnimalBanho;
    private javax.swing.JList<String> listIdAnimalCons;
    private javax.swing.JList<String> listIdade;
    private javax.swing.JList<String> listNome;
    private javax.swing.JList<String> listNumCons;
    private javax.swing.JList<String> listPeso;
    private javax.swing.JList<String> listVacinado;
    private javax.swing.JList<String> listValorBanho;
    private javax.swing.JList<String> listValorCons;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JTabbedPane tbAnimal;
    private javax.swing.JTextField tfAttEndereco;
    private javax.swing.JTextField tfAttIdade;
    private javax.swing.JPasswordField tfAttSenha;
    private javax.swing.JFormattedTextField tfAttTelefone;
    private javax.swing.JPasswordField tfSenhaAtual;
    // End of variables declaration//GEN-END:variables
    
    protected void passagem(String cpf){
        DonoAnimal cl = aDao.buscarClientePorCpf(cpf);
        
        labNomeC.setText(cl.getNome());
        labCpfC.setText(cl.getCpf());
        labIdadeC.setText(Integer.toString(cl.getIdade()));
        labEmailC.setText(cl.getEmail());
        labEnderecoC.setText(cl.getEndereco());
        labTelefoneC.setText(cl.getTelefone());
        labSenha.setText("********");
        
        this.senha = cl.getSenha();
        this.cpfCl = cpf;
    }
    
    protected void passagemAnimal(ArrayList<Animal> animais){
        animaisP = animais;
        if(animais.size()==0){
            JOptionPane.showMessageDialog(rootPane, "Não há nenhum animal cadastrado!");
        }
        else{
            String[] nomes = new String[animais.size()];
            String[] especies = new String[animais.size()];
            String[] idades = new String[animais.size()];
            String[] pesos = new String[animais.size()];
            String[] vacinados = new String[animais.size()];
            String[] cartoes = new String[animais.size()];
            for (int i = 0; i < animais.size(); i++) {
                nomes[i] = animais.get(i).getNome();
                especies[i] = animais.get(i).getEspecie();
                idades[i] = Integer.toString(animais.get(i).getIdade())+" anos";
                pesos[i] = Float.toString(animais.get(i).getPeso())+" kg";
                if(animais.get(i).isVacinado())
                    vacinados[i] = "Sim";
                else
                    vacinados[i] = "Não";
                cartoes[i] = Integer.toString(animais.get(i).getIdAnimal());
            }
            
            listNome.setListData(nomes);
            listEspecie.setListData(especies);
            listIdade.setListData(idades);
            listPeso.setListData(pesos);
            listVacinado.setListData(vacinados);
            listID.setListData(cartoes);
        }
    }
    
    protected void passagemBanho(ArrayList<Banho> banhos){
        banhosP = banhos;
        if(banhos.size()>0){
            String[] cpfAuxs = new String[banhos.size()];
            String[] ids = new String[banhos.size()];
            String[] datas = new String[banhos.size()];
            String[] horarios = new String[banhos.size()];
            String[] valores = new String[banhos.size()];

            for (int i = 0; i < banhos.size(); i++) {
                cpfAuxs[i] = banhos.get(i).getCpfAuxiliar();
                ids[i] = Integer.toString(banhos.get(i).getIdAnimal());
                datas[i] = banhos.get(i).getData();
                horarios[i] = banhos.get(i).getHorario();
                valores[i] = "R$ " + Float.toString(banhos.get(i).getValor());

            }

            listCpfAux.setListData(cpfAuxs);
            listIdAnimalBanho.setListData(ids);
            listDataBanho.setListData(datas);
            listHorarioBanho.setListData(horarios);
            listValorBanho.setListData(valores);
        }    
    }
    
    void passagemConsulta(ArrayList<Consulta> consultas) {
        consultasP = consultas;
        if(consultas.size()>0){
            String[] idCons = new String[consultas.size()];
            String[] crmvs = new String[consultas.size()];
            String[] idsAn = new String[consultas.size()];
            String[] datas = new String[consultas.size()];
            String[] horarios = new String[consultas.size()];
            String[] valores = new String[consultas.size()];

            for (int i = 0; i < consultas.size(); i++) {
                idCons[i] = Integer.toString(consultas.get(i).getIdConsulta());
                crmvs[i] = consultas.get(i).getCRMVvet();
                idsAn[i] = Integer.toString(consultas.get(i).getIdAnimal());
                datas[i] = consultas.get(i).getData();
                horarios[i] = consultas.get(i).getHorario();
                valores[i] = "R$ " + Float.toString(consultas.get(i).getValor());
            }

            listNumCons.setListData(idCons);
            listCrmvCons.setListData(crmvs);
            listIdAnimalCons.setListData(idsAn);
            listDataCons.setListData(datas);
            listHorarioCons.setListData(horarios);
            listValorCons.setListData(valores);
        }
    }

    private void cadastrarAnimal() {
        TelaCadastroAnimal t2 = new TelaCadastroAnimal();
        t2.passagemCpf(labCpfC.getText());
        t2.passagemArrays(animaisP, banhosP, consultasP);
        t2.setVisible(true);
        this.dispose();
    }
    
    private void excluirAnimal(){
        TelaExcluirAnimal t = new TelaExcluirAnimal();
        t.passagemInfos(labCpfC.getText(), senha);
        t.passagemArrays(animaisP, banhosP, consultasP);
        t.setVisible(true);
        this.dispose();
    }

    private void excluirConta(){
        TelaExcluirConta t = new TelaExcluirConta();
        t.passagemExcluir("Cliente");
        t.passagemCliente(senha, labCpfC.getText());
        t.setVisible(true);
        this.dispose();
    }

    private void atualizar() {
        if(!(tfSenhaAtual.getText().equals(senha))){
            JOptionPane.showMessageDialog(rootPane, "Senha Atual Incorreta!");
        }else if("".equals(tfAttEndereco.getText()) && ("(  )     -    ".equals(tfAttTelefone.getText())) 
                && ("".equals(tfAttIdade.getText())) && ("".equals(tfAttSenha.getText()))){
            JOptionPane.showMessageDialog(rootPane, "Insira alguma atualização!");
        }else{
            if(!("".equals(tfAttEndereco.getText())))
                attEndereco();    
            if(!("(  )     -    ".equals(tfAttTelefone.getText())))
                attTelefone();
            if(!("".equals(tfAttIdade.getText())))
                attIdade();
            if(!("".equals(tfAttSenha.getText())))
                attSenha();
            sair();
        }   
    }

    private void attEndereco() {
        aDao.atualizarEndereco(cpfCl, tfAttEndereco.getText());
    }

    private void attTelefone() {
        aDao.atualizarTelefone(cpfCl, tfAttTelefone.getText());
    }

    private void attIdade() {
        aDao.atualizarIdade(cpfCl, Integer.parseInt(tfAttIdade.getText()));
    }

    private void attSenha() {
        aDao.atualizarSenha(cpfCl, tfAttSenha.getText());
    }

    private void sair() {
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }

    private void limpar() {
        tfAttEndereco.setText("");
        tfAttTelefone.setText("");
        tfAttIdade.setText("");
        tfAttSenha.setText("");
    }
    
}
