/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projetopetshop.view;

import br.inatel.projetopetshop.DAO.AtendenteDAO;
import br.inatel.projetopetshop.DAO.AuxiliarDAO;
import br.inatel.projetopetshop.DAO.DonoAnimalDAO;
import br.inatel.projetopetshop.DAO.VeterinarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Juninho
 */
public class TelaExcluirConta extends javax.swing.JFrame {
    
    private static String pessoa;
    private static String senha;
    private static String cpf;
    

    /**
     * Creates new form TelaExcluirAtendente
     */
    public TelaExcluirConta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        btnExcluir = new javax.swing.JButton();
        tfCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true), "Excluir Minha Conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Digite sua senha para excluir:");

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tfCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfCancelar.setForeground(new java.awt.Color(0, 0, 0));
        tfCancelar.setText("Cancelar");
        tfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(tfCancelar))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(tfCancelar))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCancelarActionPerformed
        continuarLogado();
    }//GEN-LAST:event_tfCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExcluirConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tfCancelar;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
    
    protected void passagemExcluir(String pessoa){
        this.pessoa = pessoa;
    }
    
    protected void passagemAtendente(String senha, String cpfAtendente){
        this.senha = senha;
        this.cpf = cpfAtendente;
    }
    
    protected void passagemAuxiliar(String senha, String cpfAux){
        this.senha = senha;
        this.cpf = cpfAux;
    }
    
    protected void passagemCliente(String senha, String cpfCliente){
        this.senha = senha;
        this.cpf = cpfCliente;
    }
    
    protected void passagemVeterinario(String senha, String cpfVet){
        this.senha = senha;
        this.cpf = cpfVet;
    }
    
    private void excluir() {
        if(pessoa.equals("Atendente")){
            excluirAtendente();
        }else if(pessoa.equals("Auxiliar")){
            excluirAuxiliar();
        }else if(pessoa.equals("Cliente")){
            excluirCliente();
        }else if(pessoa.equals("Veterinario")){
            excluirVeterinario();
        }
    }

    private void excluirAtendente() {
        if("".equals(tfSenha.getText()))
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo corretamente!");
        else if(!(senha.equals(tfSenha.getText()))){
            JOptionPane.showMessageDialog(rootPane, "Senha incorreta!");
        }else if(senha.equals(tfSenha.getText())){
            AtendenteDAO atDao = new AtendenteDAO();
            atDao.deletarAtendente(cpf);
            JOptionPane.showMessageDialog(rootPane, "Conta excluida com sucesso!");
            mudarTela();
        }
    }
    
    private void excluirAuxiliar() {
        if("".equals(tfSenha.getText()))
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo corretamente!");
        else if(!(senha.equals(tfSenha.getText()))){
            JOptionPane.showMessageDialog(rootPane, "Senha incorreta!");
        }else if(senha.equals(tfSenha.getText())){
            AuxiliarDAO auDao = new AuxiliarDAO();
            auDao.deletarAuxiliar(cpf);
            JOptionPane.showMessageDialog(rootPane, "Conta excluida com sucesso!");
            mudarTela();
        } 
    }

    private void excluirCliente() {
        if("".equals(tfSenha.getText()))
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo corretamente!");
        else if(!(senha.equals(tfSenha.getText()))){
            JOptionPane.showMessageDialog(rootPane, "Senha incorreta!");
        }else if(senha.equals(tfSenha.getText())){
            DonoAnimalDAO anDao = new DonoAnimalDAO();
            anDao.deletarCliente(cpf);
            JOptionPane.showMessageDialog(rootPane, "Conta excluida com sucesso!");
            mudarTela();
        }
    }

    private void excluirVeterinario() {
        if("".equals(tfSenha.getText()))
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo corretamente!");
        else if(!(senha.equals(tfSenha.getText()))){
            JOptionPane.showMessageDialog(rootPane, "Senha incorreta!");
        }else if(senha.equals(tfSenha.getText())){
            VeterinarioDAO vetDao = new VeterinarioDAO();
            vetDao.deletarVeterinario(cpf);
            JOptionPane.showMessageDialog(rootPane, "Conta excluida com sucesso!");
            mudarTela();
        }
    }
    
    private void mudarTela() {
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }

    private void continuarLogado() {
        if(pessoa.equals("Atendente")){
            TelaInfoAtendente t = new TelaInfoAtendente();
            t.passagem(cpf);
            t.setVisible(true);
            this.dispose();
        }else if(pessoa.equals("Auxiliar")){
            TelaInfoAuxiliar t = new TelaInfoAuxiliar();
            t.passagem(cpf);
            t.setVisible(true);
            this.dispose();
        }else if(pessoa.equals("Cliente")){
            TelaInfoCliente t = new TelaInfoCliente();
            t.passagem(cpf);
            t.setVisible(true);
            this.dispose();
        }else if(pessoa.equals("Veterinario")){
            TelaInfoVeterinario t = new TelaInfoVeterinario();
            t.passagem(cpf);
            t.setVisible(true);
            this.dispose();
        }
    }
    

}
