/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projetopetshop.view;
import br.inatel.projetopetshop.DAO.AnimalDAO;
import br.inatel.projetopetshop.DAO.AtendenteDAO;
import br.inatel.projetopetshop.DAO.AuxiliarDAO;
import br.inatel.projetopetshop.DAO.BanhoDAO;
import br.inatel.projetopetshop.DAO.ConsultaDAO;
import br.inatel.projetopetshop.DAO.DonoAnimalDAO;
import br.inatel.projetopetshop.DAO.VeterinarioDAO;
import br.inatel.projetopetshop.model.Animal;
import br.inatel.projetopetshop.model.Atendente;
import br.inatel.projetopetshop.model.Auxiliar;
import br.inatel.projetopetshop.model.Banho;
import br.inatel.projetopetshop.model.Consulta;
import br.inatel.projetopetshop.model.DonoAnimal;
import br.inatel.projetopetshop.model.Veterinario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juninho
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labEmail = new javax.swing.JLabel();
        labSenha = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        tfEmail = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        labEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labEmail.setForeground(new java.awt.Color(0, 0, 0));
        labEmail.setText("E-mail:");

        labSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labSenha.setForeground(new java.awt.Color(0, 0, 0));
        labSenha.setText("Senha:");

        tfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labSenha)
                            .addComponent(labEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSenha)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogin)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(48, 48, 48)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSenha)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCancelar))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSenhaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        mudarTela();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labSenha;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables

    private void mudarTela() {
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }

    private void logar() {
        if("".equals(tfEmail.getText()) || "".equals(tfSenha.getText())){
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente!");
        }
        else if(tfEmail.getText().contains("@atendente.com")){
            AtendenteDAO atDao = new AtendenteDAO();
            Atendente at = new Atendente(" ", " ", " ", " ", " ", " ", " ");
            at = atDao.buscarAtendentePorEmail(tfEmail.getText(), tfSenha.getText());
            if(at != null){
                TelaInfoAtendente t = new TelaInfoAtendente();
                t.passagem(at.getCpf());
                t.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Email não encontrado!");
            }
        }
        else if(tfEmail.getText().contains("@auxiliar.com")){
            AuxiliarDAO auxDao = new AuxiliarDAO();
            Auxiliar aux = new Auxiliar(" ", " ", " ", " ", " ", " ", " ", " ", " ");
            aux = auxDao.buscarAuxiliarPorEmail(tfEmail.getText(), tfSenha.getText());
            if(aux != null){
                TelaInfoAuxiliar t = new TelaInfoAuxiliar();
                t.passagem(aux.getCpf());
                t.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Email não encontrado!");
            }
        }
        else if(tfEmail.getText().contains("@cliente.com")){
            DonoAnimalDAO donoDao = new DonoAnimalDAO();
            DonoAnimal don = new DonoAnimal(" ", " ", " ", " ", 0, " ", " ");
            don = donoDao.buscarClientePorEmail(tfEmail.getText(), tfSenha.getText());
            
            AnimalDAO anDao = new AnimalDAO();
            ArrayList<Animal> animais = anDao.buscaAnimalLogin(don.getCpf());
            
            BanhoDAO bnDao = new BanhoDAO();
            ArrayList<Banho> banhos = bnDao.buscaBanhos(don.getCpf());
            
            ConsultaDAO cnDao = new ConsultaDAO();
            ArrayList<Consulta> consultas = cnDao.buscaConsultas(don.getCpf());
            
            if(don != null){
                TelaInfoCliente t = new TelaInfoCliente();
                t.passagemAnimal(animais);
                t.passagemBanho(banhos);
                t.passagemConsulta(consultas);
                t.passagem(don.getCpf());
                t.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Email não encontrado!");
            }
        }
        else if(tfEmail.getText().contains("@veterinario.com")){
            VeterinarioDAO vetDao = new VeterinarioDAO();
            Veterinario vet = new Veterinario(" ", " ", " ", " ", " ", " ", " ", " ", " ");
            vet = vetDao.buscarVeterinarioPorEmail(tfEmail.getText(), tfSenha.getText());
            if(vet != null){
                TelaInfoVeterinario t = new TelaInfoVeterinario();
                t.passagem(vet.getCpf());
                t.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Email não encontrado!");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Email não encontrado!");
        }
    }

}
